### ISSUE TITLE
The DM Screen function on D&D Beyond is not working. The stats don't appear under the characters on the campaign page, and the DM Screen Link pulls up an empty window.

### ISSUE THREAD

**Issue by wermestat** [AshDevFr/encounters_app#5] opened 2020-06-14 19:05 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Kalaallit-Nunaat** [comment] 2020-06-16 01:05
So I'm adding to the post as asked in the dndbeyond forum. I've attached a screen shot of what I'm seeing. Thanks!
![Screen Shot 2020-06-15 at 21 04 22](https://user-images.githubusercontent.com/66980697/84720361-da69db80-af4b-11ea-82b7-3b39c95c1850.png)

**Comment by Windexhammer** [comment] 2020-06-16 03:58
Not sure if this is helpful, but I can confirm that I'm seeing the identical behaviour on Chrome in Windows 10. Chrome Version 83.0.4103.106 (Official Build) (64-bit).

**Comment by AshDevFr** [comment] 2020-06-16 18:00
Hi, thank you for creating an issue.
Unfortunately, the DnDBeyond team removed the endpoint used to access the json.
What it means is that the extension will need a refactor to be able to work with either the endpoint still available, or find another way.

In the meantime you can try this app (https://encounters.4sh.dev) that allow you to create a DM Screen. I use another endpoint with this app and so far it's still working. Let's hope they don't remove it.

It's really a sad news that they are blocking developers form trying to make things better.

**Comment by AshDevFr** [comment] 2020-06-22 16:10
Hi, the bug was caused by a change made by the dndbeyond team. I deployed a fix yesterday night. Please take a look (v1.2.0 of the extension).
Closing this issue. Feel free to create a new one if it is still failing with the new version.

**Closed as completed by AshDevFr** 2020-06-22 16:10 UTC
Labels: bug
