### ISSUE TITLE
JSON no more accesible

### ISSUE THREAD

**Issue by franciscorba** [AshDevFr/encounters_app#4] opened 2020-06-10 17:54 UTC
It seems that D&D Beyond has remove the access to the character sheets JSON.

**Comment by AshDevFr** [comment] 2020-06-16 18:00
Hi @franciscorba, is it a bug happening in the chrome extension ?
You are right they did remove one endpoint to access the json.

I use another endpoint with the app available at https://encounters.4sh.dev and so far it's still working. Let's hope they don't remove it.

It's really a sad news that they are blocking developers form trying to make things better.

**Comment by franciscorba** [comment] 2020-06-16 18:22
Yes, the chrome extension doesn't work anymore after they block the endpoint. It doesn't add the info to the campaign page and if we click the dm screen button it gives and empty one. It also triggers the anti-bot message from DDB.

**Comment by AshDevFr** [comment] 2020-06-22 16:10
Hi, the bug was caused by a change made by the dndbeyond team. I deployed a fix yesterday night. Please take a look (v1.2.0 of the extension).
Closing this issue. Feel free to create a new one if it is still failing with the new version.

**Closed as completed by AshDevFr** 2020-06-22 16:10 UTC
Labels: bug, extension
